name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make test-gendiff
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: 20ee1653129530b1b6f8266d7974ed69f398a6195d5a05e32a00c2cb1d0f93ab
        with:
          coverageCommand: make test-coverage

